version: "3.8"
services: 
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shipping
    ports:
      - 5432:5432
    restart: on-failure
    networks:
      - internal