version: "3.3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shipping
    ports:
      - 5432:5432
    restart: on-failure
    networks:
      - internal
  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
    networks:
      - internal
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    working_dir: "/usr/api"
    ports:
      - 12345:12345
    volumes:
      - ./:/usr/api
      - /usr/api/node_modules
    restart: on-failure
    environment:
      PORT: 12345
      DB_HOST: postgres
      DB_NAME: shipping
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_PASSWORD: supersecret
      NODE_ENV: development
      REDIS_CONNECTION_STRING: redis://redis:6379
      SOURCE_ZIP_CODE: 7034911
    networks:
      - internal
networks:
  internal: null
