const Router = require('koa-router')
const { errorHandler, authorizationChecker, accessLogger } = require('./middlewares')
const addresses = require('./addresses')
const authentication = require('./authentication')
const docs = require('./docs')

module.exports = new Router()
    .use(accessLogger)
    .use('/docs', docs)
    .use(errorHandler)
    .use('/authentication', authentication)
    .use(authorizationChecker)
    .use('/addresses', addresses)
    .routes()
