const Router = require('koa-router')
const { errorHandler } = require('./middlewares')
const addresses = require('./addresses')
const authentication = require('./authentication')

module.exports = new Router()
    .use(errorHandler)
    .use('/authentication', authentication)
    .use('/addresses', addresses)
    .routes()
